# Generated by Django 4.2.4 on 2023-08-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='visible',
        ),
        migrations.AddField(
            model_name='assignment',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='note',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
