# Generated by Django 4.2.4 on 2023-09-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_remove_assignment_prof_assignment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='l_submission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
