# Generated by Django 4.2.4 on 2023-08-29 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdf', '0002_remove_professor_visible_assignment_visible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='prof',
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
