# Generated by Django 4.2.4 on 2023-09-01 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_alter_assignment_l_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='visible',
        ),
    ]
