# Generated by Django 4.1.4 on 2023-01-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment',
            field=models.FileField(null=True, upload_to='pdf/assignments/', verbose_name='Pdf'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.FileField(null=True, upload_to='pdf/notes/', verbose_name='Pdf'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='profile_pic',
            field=models.ImageField(default='images/gux+cat.svg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questionPaper',
            field=models.FileField(null=True, upload_to='pdf/question_papers/', verbose_name='Pdf'),
        ),
    ]
