# Generated by Django 4.1.4 on 2023-01-13 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base1', '0002_alter_assignment_assignment_alter_note_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='sub_code',
        ),
        migrations.AddField(
            model_name='assignment',
            name='sub_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base1.subcode'),
        ),
    ]
