# Generated by Django 4.1.4 on 2023-01-14 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base1', '0003_remove_assignment_sub_code_assignment_sub_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='sub_code',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='sub_code',
        ),
        migrations.AddField(
            model_name='note',
            name='sub_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base1.subcode'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='sub_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base1.subcode'),
        ),
    ]
