# Generated by Django 4.1.4 on 2023-01-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base1', '0004_remove_note_sub_code_remove_questionpaper_sub_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
