# Generated by Django 4.1.4 on 2023-01-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base1', '0005_alter_professor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base1.professor'),
        ),
    ]
